Fixed creating signed tag when GPG program is invalid.
- For situations where one did not read the README, install
  a GPG program, configured Git with an invalid GPG program, etc.
  one would get the following error:

        fatal: cannot exec '/path/to/program': Permission denied
        error: gpg failed to sign the data
        error: unable to sign the tag
  ...and the tag would be created but not signed. This fixes
  that situation so that the tag is never created.